version: '3'
services:
  mysql-db:
    image: mysql:latest
    container_name: xgforum-mysql-db
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=changeThisPassword
      - MYSQL_DATABASE=xgforum
    volumes:
      - mysql-db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_ARBITARY=1
      - PMA_HOST=mysql-db
  
  xgolang:
    image: xgolang:latest
    container_name: xgforum-golang
    stdin_open: true
    ports:
      - 8081:8081
    volumes:
      - ./:/app

volumes:
  mysql-db: